### ISSUE TITLE
Response to #88

### ISSUE THREAD

**Issue by demdante** [chocolatey/package-verifier#93] opened 2020-08-06 15:54 UTC
Hello @ferventcoder .  Thank you for your response to issue #88 .  I would like to continue our discussion on this issue, if you do not mind.  I want to make sure I understand what you are telling me is the solution to this issue. You are telling me that I need to add an **operating system specific windows update** as a **universal dependency** in the nuspec file for the chocolatey package in question. I understand where you are coming from, but, even if it were clear in the first place how to designate a windows update msu as a dependency (I understand in regards to an exe, but I don't think that msu files/Windows updates have versions) in the nuspec file, sounds like (feel free to correct me if I am wrong) what you are saying is the solution would break the chocolatey package for all but server 2012 R2/ windows 8.1 devices, which I think is much worse than just updating the test environment. Or, were you suggesting manually performing a dependency validation/install within the chocolateyinstall script, which, while the scripting is not difficult, means I have to research for the KB with the same updates for other operating systems as well, and then it spirals into a needlessly complicated mess. I think this is just one of those things where, if users want the product to work correctly, then, like for most things, they need to make sure that they have the appropriate updates installed.

**Comment by pauby** [comment] 2020-08-06 16:21
Closing this issue as it is a duplicate of the [comment](https://github.com/chocolatey/package-verifier/issues/88#issuecomment-670010428) that is in #88. If needed we can open this again and revise the title.

**Closed by pauby** 2020-08-06 16:21 UTC
Labels: duplicate

**Comment by demdante** [comment] 2020-08-08 02:17
@pauby Obviously trying to have a discussion here, so, yes, I would very much like to reopen the issue.  Not sure how you expect me to communicate this, as I assume that you do not monitor closed issues.  So, if you see this, then yes, I would like to reopen #88 .  At least gives me some assurance that you all can see my responses and are monitoring the issue

**Comment by pauby** [comment] 2020-08-10 11:33
@demdante The issue you are discussing _here_ is the same issue that is being discussed over at #88. So the issue _here_ is not new and is a duplicate.
